package ojt.management.seeding;

import com.github.javafaker.Faker;
import ojt.management.common.enums.RoleEnum;
import ojt.management.common.payload.request.AccountRequest;

import java.util.Arrays;
import java.util.List;

public class UserData {
    public static List<AccountRequest> getSeedData(){
        Faker faker = new Faker();
        String initialPassword = "123456";
        List<AccountRequest> accountRequests = Arrays.asList(
                new AccountRequest("thanhthu0321@gmail.com", initialPassword, "Thu", RoleEnum.SYS_ADMIN.name(), faker.phoneNumber().subscriberNumber(12), null),
                new AccountRequest("student1@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150099", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student2@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150098", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student3@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150097", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student4@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150096", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student5@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150095", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student6@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150094", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student7@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150093", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student8@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150092", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student9@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150091", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student10@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150090", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student11@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150102", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student12@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150103", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student13@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150104", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student14@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150105", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student15@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150106", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student16@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150107", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student17@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150108", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student18@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150109", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student19@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150110", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student20@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150111", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student21@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150112", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student22@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150113", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student23@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150114", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student24@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150115", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student25@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150116", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student26@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150117", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student27@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150118", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student28@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150119", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student29@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150120", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student30@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150121", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student31@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150122", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student32@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "BA150123", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student33@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150123", Long.valueOf(2), Long.valueOf(1), null),
                new AccountRequest("student34@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150124", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student35@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150125", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student36@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150126", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student37@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150127", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student38@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150128", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student39@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150129", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student40@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150130", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student41@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150131", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student42@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150132", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student43@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150133", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student44@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150134", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student45@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150135", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student46@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150136", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student47@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150137", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student48@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150138", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student49@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150139", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("student50@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.STUDENT.name(), faker.phoneNumber().subscriberNumber(12), faker.address().fullAddress(), "SE150140", Long.valueOf(1), Long.valueOf(1), null),
                new AccountRequest("representative1@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.COMPANY_REPRESENTATIVE.name(), CompanyData.getSeedData().get(0).getName(), CompanyData.getSeedData().get(0).getDescription(), CompanyData.getSeedData().get(0).getAddress(), faker.phoneNumber().subscriberNumber(12), null),
                new AccountRequest("representative2@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.COMPANY_REPRESENTATIVE.name(), CompanyData.getSeedData().get(1).getName(), CompanyData.getSeedData().get(1).getDescription(), CompanyData.getSeedData().get(1).getAddress(), faker.phoneNumber().subscriberNumber(12), null),
                new AccountRequest("representative3@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.COMPANY_REPRESENTATIVE.name(), CompanyData.getSeedData().get(2).getName(), CompanyData.getSeedData().get(2).getDescription(), CompanyData.getSeedData().get(2).getAddress(), faker.phoneNumber().subscriberNumber(12), null),
                new AccountRequest("representative4@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.COMPANY_REPRESENTATIVE.name(), CompanyData.getSeedData().get(3).getName(), CompanyData.getSeedData().get(3).getDescription(), CompanyData.getSeedData().get(3).getAddress(), faker.phoneNumber().subscriberNumber(12), null),
                new AccountRequest("representative5@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.COMPANY_REPRESENTATIVE.name(), CompanyData.getSeedData().get(4).getName(), CompanyData.getSeedData().get(4).getDescription(), CompanyData.getSeedData().get(4).getAddress(), faker.phoneNumber().subscriberNumber(12), null),
                new AccountRequest("representative6@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.COMPANY_REPRESENTATIVE.name(), CompanyData.getSeedData().get(5).getName(), CompanyData.getSeedData().get(5).getDescription(), CompanyData.getSeedData().get(5).getAddress(), faker.phoneNumber().subscriberNumber(12), null),
                new AccountRequest("representative7@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.COMPANY_REPRESENTATIVE.name(), CompanyData.getSeedData().get(6).getName(), CompanyData.getSeedData().get(6).getDescription(), CompanyData.getSeedData().get(6).getAddress(), faker.phoneNumber().subscriberNumber(12), null),
                new AccountRequest("representative8@gmail.com", initialPassword, faker.name().fullName(), RoleEnum.COMPANY_REPRESENTATIVE.name(), CompanyData.getSeedData().get(7).getName(), CompanyData.getSeedData().get(7).getDescription(), CompanyData.getSeedData().get(7).getAddress(), faker.phoneNumber().subscriberNumber(12), null)
        );
        return accountRequests;
    }
}
